"""gc grace clock

Block G. The garbage collector waits a grace period before deleting a `refcount = 0`
blob, and until now there was nothing to measure that period against.

`blob_gc_idx` was `(created_at) WHERE refcount = 0`, and `created_at` is when the blob
was FIRST STORED. Nothing ever updates it. So a blob written two years ago whose last
reference was deleted one second ago passes `created_at < now() - 24h` on the very next
sweep — no wait at all — while a blob written an hour ago is held for 23 more hours for
no reason. The protection was strongest exactly where it was least needed.

Worse, the case HLD §9.7 and ARCHITECTURE diagram 14 use to justify the grace period is
the case it fails on. "Mailbox A deletes while mailbox B is uploading the same file"
means B is uploading a file we already hold — so the blob is old, the age check passes,
and the diagram's SAFE outcome does not happen.

This adds the clock the design always assumed existed: `refcount_zeroed_at`, the moment
the blob BECAME garbage. The invariant is

    refcount_zeroed_at IS NULL   <=>   refcount > 0

maintained in two places: this trigger on the way down, and `routing.deliver()` on the
way up.

`DEFAULT now()` is not cosmetic. A blob stored by block C whose every recipient turned
out to be unroutable never fires this trigger at all. Without the default it would sit at
NULL for ever and GC would never collect it — a permanent leak of exactly the bytes GC
exists to reclaim. With it, such a blob is collectable one grace period after it was
written, which is correct: it has been garbage since the moment it was stored.

**What the grace period is actually for, since this migration changes the answer.** It is
NOT what makes the concurrent-upload race safe — the foreign key is. `message_attachment`
references `blob` with NO ACTION, so its key-share lock either blocks GC's delete until
the writer commits (after which `WHERE refcount = 0` matches nothing) or blocks the writer
until GC commits (after which the writer fails loudly and Kafka retries). That holds at
any grace period, including zero. What the grace period buys is a 24-hour window for an
operator to notice a GC bug before the bytes are gone. Different justification, still
worth having — and worth writing down, or the next person deletes it as redundant.

Revision ID: 9c3e5a1d7b42
Revises: 4f1a9c2b8e07
Create Date: 2026-08-10

"""
from typing import Sequence, Union

from alembic import op

revision: str = "9c3e5a1d7b42"
down_revision: Union[str, Sequence[str], None] = "4f1a9c2b8e07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
ALTER TABLE blob ADD COLUMN refcount_zeroed_at TIMESTAMPTZ DEFAULT now();

-- Establish the invariant on rows that already exist. Anything at zero has been garbage
-- for an unknown length of time; now() is the conservative choice, since it gives those
-- blobs a full grace period rather than making them collectable instantly.
UPDATE blob SET refcount_zeroed_at = now()  WHERE refcount <= 0;
UPDATE blob SET refcount_zeroed_at = NULL   WHERE refcount >  0;

DROP INDEX IF EXISTS blob_gc_idx;
CREATE INDEX blob_gc_idx ON blob (refcount_zeroed_at) WHERE refcount = 0;
    """)

    # Written by hand, not autogenerated: --autogenerate cannot see triggers at all, and
    # this one is the only thing that lowers blob.refcount and mailbox.used_bytes.
    op.execute("""
CREATE OR REPLACE FUNCTION mailbox_message_deleted() RETURNS TRIGGER AS $$
BEGIN
    UPDATE blob b
       SET refcount = b.refcount - 1,
           -- The clock. CASE yields NULL when the refcount is still positive, which IS
           -- the invariant: NULL means "in use". Set on the way down here, cleared on
           -- the way up in routing.deliver().
           refcount_zeroed_at = CASE WHEN b.refcount - 1 <= 0 THEN now() END
      FROM message_attachment ma
     WHERE ma.message_id  = OLD.message_id
       AND b.reseller_id  = ma.reseller_id
       AND b.hash         = ma.blob_hash;

    -- COALESCE because the message row may already be gone if this delete arrived
    -- as a cascade from the message itself.
    UPDATE mailbox
       SET used_bytes = GREATEST(
               0,
               used_bytes - COALESCE(
                   (SELECT size_bytes FROM message WHERE id = OLD.message_id), 0)
           )
     WHERE id = OLD.mailbox_id;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    op.execute("""
CREATE OR REPLACE FUNCTION mailbox_message_deleted() RETURNS TRIGGER AS $$
BEGIN
    UPDATE blob b
       SET refcount = b.refcount - 1
      FROM message_attachment ma
     WHERE ma.message_id  = OLD.message_id
       AND b.reseller_id  = ma.reseller_id
       AND b.hash         = ma.blob_hash;

    UPDATE mailbox
       SET used_bytes = GREATEST(
               0,
               used_bytes - COALESCE(
                   (SELECT size_bytes FROM message WHERE id = OLD.message_id), 0)
           )
     WHERE id = OLD.mailbox_id;

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;
    """)

    op.execute("""
DROP INDEX IF EXISTS blob_gc_idx;
ALTER TABLE blob DROP COLUMN IF EXISTS refcount_zeroed_at;
CREATE INDEX blob_gc_idx ON blob (created_at) WHERE refcount = 0;
    """)
